name: innenu
description: A gift for NENU students.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  # https://github.com/material-components/material-components-flutter-adaptive/tree/develop/adaptive_breakpoints
  adaptive_breakpoints: ^0.1.1

  # https://github.com/brendan-duncan/archive
  archive: ^3.1.2

  # https://github.com/Baseflow/flutter_cached_network_image
  cached_network_image: ^3.0.0

  # https://github.com/serenader2014/flutter_carousel_slider
  carousel_slider: ^4.0.0-nullsafety.0

  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0

  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3

  flutter:
    sdk: flutter

  # https://github.com/SunnyApp/flutter_contact
  flutter_contacts: ^1.1.1+2

  flutter_localizations:
    sdk: flutter

  # SVG 支持: https://github.com/dnfield/flutter_svg
  flutter_svg: ^1.1.0

  json_annotation: ^4.3.0

  # https://github.com/dart-lang/logging
  logging: ^1.0.1

  # https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0

  # https://github.com/dart-lang/path
  path: ^1.8.0

  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.1

  # https://github.com/Baseflow/flutter-permission-handler
  permission_handler: ^9.2.0

  provider: ^6.0.1
  shared_preferences: ^2.0.5

  # Flutter shared_preferences plugin util https://github.com/Sky24n/sp_util
  sp_util: ^2.0.3

  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.0.3

  # WebView 插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^3.0.4

dev_dependencies:
  # https://pub.flutter-io.cn/packages/build_runner
  build_runner: ^2.0.1

  flutter_test:
    sdk: flutter

  # https://pub.flutter-io.cn/packages/json_serializable
  json_serializable: ^6.0.1

  # https://pub.flutter-io.cn/packages/test
  test: ^1.17.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/components/doc/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
